In [30]:
import sagemaker
from sklearn.model_selection import train_test_split
import boto3
import pandas as pd

region = 'eu-north-1'
boto_session = boto3.Session(region_name=region)
sm_boto3 = boto3.client('sagemaker', region_name=region)
sess = sagemaker.Session(boto_session=boto_session)
bucket = 'my-first-aibucket'
print("using bucket: " + bucket)

INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials

using bucket: my-first-aibucket

In [31]:
import boto3
s3 = boto3.client('s3', region_name='eu-north-1')
response = s3.list_objects_v2(Bucket='my-first-aibucket')
for obj in response.get('Contents', []):
    print(obj['Key'])

sagemaker/sklearn-container/test-V-1.csv
sagemaker/sklearn-container/train-V-1.csv

In [32]:
df = pd.read_csv('train (1).csv')

In [33]:
df.head()

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,...,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi,price_range
0,842,0,2.2,0,1,0,7,0.6,188,2,...,20,756,2549,9,7,19,0,0,1,1
1,1021,1,0.5,1,0,1,53,0.7,136,3,...,905,1988,2631,17,3,7,1,1,0,2
2,563,1,0.5,1,2,1,41,0.9,145,5,...,1263,1716,2603,11,2,9,1,1,0,2
3,615,1,2.5,0,0,0,10,0.8,131,6,...,1216,1786,2769,16,8,11,1,0,0,2
4,1821,1,1.2,0,13,1,44,0.6,141,2,...,1208,1212,1411,8,2,15,1,1,0,1

In [34]:
df.shape

(2000, 21)

In [35]:
df['price_range'].value_counts(normalize=False)

price_range
1    500
2    500
3    500
0    500
Name: count, dtype: int64

In [36]:
df.columns

Index(['battery_power', 'blue', 'clock_speed', 'dual_sim', 'fc', 'four_g',
       'int_memory', 'm_dep', 'mobile_wt', 'n_cores', 'pc', 'px_height',
       'px_width', 'ram', 'sc_h', 'sc_w', 'talk_time', 'three_g',
       'touch_screen', 'wifi', 'price_range'],
      dtype='str')

In [37]:
df.shape

(2000, 21)

In [38]:
df.isnull().mean()* 100

battery_power    0.0
blue             0.0
clock_speed      0.0
dual_sim         0.0
fc               0.0
four_g           0.0
int_memory       0.0
m_dep            0.0
mobile_wt        0.0
n_cores          0.0
pc               0.0
px_height        0.0
px_width         0.0
ram              0.0
sc_h             0.0
sc_w             0.0
talk_time        0.0
three_g          0.0
touch_screen     0.0
wifi             0.0
price_range      0.0
dtype: float64

In [39]:
features = list(df.columns)
features

['battery_power',
 'blue',
 'clock_speed',
 'dual_sim',
 'fc',
 'four_g',
 'int_memory',
 'm_dep',
 'mobile_wt',
 'n_cores',
 'pc',
 'px_height',
 'px_width',
 'ram',
 'sc_h',
 'sc_w',
 'talk_time',
 'three_g',
 'touch_screen',
 'wifi',
 'price_range']

In [40]:
label = features.pop(-1)
label

'price_range'

In [41]:
x = df[features]
y = df[label]

In [42]:
x.head()

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,pc,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi
0,842,0,2.2,0,1,0,7,0.6,188,2,2,20,756,2549,9,7,19,0,0,1
1,1021,1,0.5,1,0,1,53,0.7,136,3,6,905,1988,2631,17,3,7,1,1,0
2,563,1,0.5,1,2,1,41,0.9,145,5,6,1263,1716,2603,11,2,9,1,1,0
3,615,1,2.5,0,0,0,10,0.8,131,6,9,1216,1786,2769,16,8,11,1,0,0
4,1821,1,1.2,0,13,1,44,0.6,141,2,14,1208,1212,1411,8,2,15,1,1,0

In [43]:
y.head()

0    1
1    2
2    2
3    2
4    1
Name: price_range, dtype: int64

In [44]:
x.shape

(2000, 20)

In [45]:
y.value_counts(normalize=False)

price_range
1    500
2    500
3    500
0    500
Name: count, dtype: int64

In [46]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [47]:
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(1600, 20) (400, 20) (1600,) (400,)

In [48]:
trainX = pd.DataFrame(X_train)
trainX[label] = y_train

testX = pd.DataFrame(X_test)
testX[label] = y_test

In [49]:
print(trainX.shape, testX.shape)

(1600, 21) (400, 21)

In [50]:
trainX.head()

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,...,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi,price_range
968,1923,0,0.5,1,7,0,46,0.5,191,1,...,767,1759,1489,10,9,3,1,1,1,1
240,633,1,2.2,0,0,1,49,0.1,139,8,...,529,1009,3560,11,1,16,1,1,1,2
819,1236,0,0.9,1,2,1,57,0.1,188,1,...,517,809,1406,14,12,20,1,0,1,0
692,781,0,1.1,0,2,0,38,0.4,198,5,...,304,1674,3508,13,8,5,0,0,1,3
420,1456,1,0.5,1,7,0,7,0.4,105,5,...,823,1104,1587,6,5,20,1,0,1,1

In [51]:
trainX.isnull().sum()

battery_power    0
blue             0
clock_speed      0
dual_sim         0
fc               0
four_g           0
int_memory       0
m_dep            0
mobile_wt        0
n_cores          0
pc               0
px_height        0
px_width         0
ram              0
sc_h             0
sc_w             0
talk_time        0
three_g          0
touch_screen     0
wifi             0
price_range      0
dtype: int64

In [52]:
testX.isnull().sum()

battery_power    0
blue             0
clock_speed      0
dual_sim         0
fc               0
four_g           0
int_memory       0
m_dep            0
mobile_wt        0
n_cores          0
pc               0
px_height        0
px_width         0
ram              0
sc_h             0
sc_w             0
talk_time        0
three_g          0
touch_screen     0
wifi             0
price_range      0
dtype: int64

In [53]:
trainX.to_csv('train-V-1.csv', index=False)
testX.to_csv('test-V-1.csv', index=False)

### We are sending the Data to S3 Bucket ###

In [54]:
import boto3
session = boto3.Session()
creds = session.get_credentials()
print(creds.access_key)

INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials

AKIAQLSZD4ELFFZZGRNR

In [55]:
sk_prefix = 'sagemaker/sklearn-container'
trainpath = sess.upload_data(path='train-V-1.csv', bucket=bucket, key_prefix=sk_prefix)
testpath = sess.upload_data(path='test-V-1.csv', bucket=bucket, key_prefix=sk_prefix)
print(trainpath)
print(testpath)

s3://my-first-aibucket/sagemaker/sklearn-container/train-V-1.csv
s3://my-first-aibucket/sagemaker/sklearn-container/test-V-1.csv

### We are writing the Script.py ###

In [56]:
%%writefile train.py

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, precision_score, recall_score, f1_score
import sklearn
import joblib
import os
import numpy as np
import pandas as pd
import boto3
import pathlib
from io import StringIO
import argparse


def model_fn(model_dir):
    clf = joblib.load(os.path.join(model_dir, "model.joblib"))
    return clf

if __name__ == "__main__":

    print("[INFO] Reading training data")
    parser = argparse.ArgumentParser()
    parser.add_argument("--n_estimators", type=int, default=100)
    parser.add_argument("--random_state", type=int, default=0)

    parser.add_argument("--model-dir", type=str, default=os.environ.get("SM_MODEL_DIR"))
    parser.add_argument("--train", type=str, default=os.environ.get("SM_CHANNEL_TRAIN"))
    parser.add_argument("--test", type=str, default=os.environ.get("SM_CHANNEL_TEST"))
    parser.add_argument("--train-file", type=str, default="train-V-1.csv")
    parser.add_argument("--test-file", type=str, default="test-V-1.csv")

    args = parser.parse_known_args()

    print("SKLearn Version: ", sklearn.__version__)
    print("Joblib Version: ", joblib.__version__)
    print("[INFO] Reading training data")
    print()
    train_df = pd.read_csv(os.path.join(args[0].train, args[0].train_file))
    test_df = pd.read_csv(os.path.join(args[0].test, args[0].test_file))

    features = list(train_df.columns)
    label = features.pop(-1)

    print("Building training and testing datasets")
    print()
    X_train = train_df[features]
    X_test = test_df[features]
    y_train = train_df[label]
    y_test = test_df[label]

    print('Colum order:')
    print(features)
    print()


    print("Label column: ", label)
    print()

    print("Data Shape:")
    print()
    print("---- SHAPE OF TRAINING DATA (85%) ----")
    print("X_train: ", X_train.shape)
    print("y_train: ", y_train.shape)
    print()
    print("---- SHAPE OF TESTING DATA (15%) ----")
    print("X_test: ", X_test.shape)
    print("y_test: ", y_test.shape)
    print()

    print("Traning Random Forest model....")
    print()
    model = RandomForestClassifier(n_estimators=args[0].n_estimators, random_state=args[0].random_state)
    model.fit(X_train, y_train)
    print()

    model_path = os.path.join(args[0].model_dir, "model.joblib")
    joblib.dump(model, model_path)
    print("Model persisted at location: ", model_path)
    print()


    y_pred = model.predict(X_test)
    test_acc = accuracy_score(y_test, y_pred)
    test_rep = classification_report(y_test, y_pred)

    print()
    print("---- Metrics Results For Testing Data ----")
    print()
    print("total Rows are: ", X_test.shape[0])
    print('[TESTING] Model Accuracy: ', test_acc)
    print('[TESTING] Classification Report: ')
    print(test_rep)

Overwriting train.py

In [57]:
from sagemaker.sklearn.estimator import SKLearn
from sagemaker import get_execution_role

role = "arn:aws:iam::024882962710:role/SageMakerExecutionRole-MobileClassification"

sklearn_estimator = SKLearn(
    entry_point='train.py',
    instance_count=1,
    role=role,
    instance_type='ml.m5.large',
    framework_version='1.2-1',
    base_job_name='sklearn-rf-classifier',
    py_version='py3',
    hyperparameters={
        'n_estimators': 100,
        'random_state': 0
    },

)

In [58]:
sklearn_estimator.fit({'train': trainpath, 'test': testpath}, wait=True)

INFO:sagemaker.telemetry.telemetry_logging:SageMaker Python SDK will collect telemetry to help us better understand our user's needs, diagnose issues, and deliver additional features.
To opt out of telemetry, please disable via TelemetryOptOut parameter in SDK defaults config. For more information, refer to https://sagemaker.readthedocs.io/en/stable/overview.html#configuring-and-using-defaults-with-the-sagemaker-python-sdk.
INFO:sagemaker:Creating training-job with name: sklearn-rf-classifier-2026-09-14-06-09-17-394

2026-09-14 06:09:29 Starting - Starting the training job...
2026-09-14 06:09:43 Starting - Preparing the instances for training...
2026-09-14 06:10:09 Downloading - Downloading input data.

### Deployment Process ###

In [59]:
sklearn_estimator.latest_training_job.wait(logs="None")
artifact = sm_boto3.describe_training_job(TrainingJobName=sklearn_estimator.latest_training_job.name)['ModelArtifacts']['S3ModelArtifacts']

print("Model artifact persisted at: ", artifact)

2026-09-14 06:12:08 Starting - Preparing the instances for training
2026-09-14 06:12:08 Downloading - Downloading the training image
2026-09-14 06:12:08 Training - Training image download completed. Training in progress.
2026-09-14 06:12:08 Uploading - Uploading generated training model
2026-09-14 06:12:08 Completed - Training job completed
Model artifact persisted at:  s3://sagemaker-eu-north-1-024882962710/sklearn-rf-classifier-2026-09-14-06-09-17-394/output/model.tar.gz

In [60]:
artifact

's3://sagemaker-eu-north-1-024882962710/sklearn-rf-classifier-2026-09-14-06-09-17-394/output/model.tar.gz'

In [61]:
from sagemaker.sklearn.model import SKLearnModel
from time import gmtime, strftime

model_name = "Custom-sklearn-model-" + strftime("%Y-%m-%d-%H-%M-%S", gmtime())
model = SKLearnModel(name = model_name,
                     model_data=artifact,
                     role=role,
                     entry_point='train.py',
                     framework_version='1.2-1',
                     py_version='py3')

print("Model Name: ", model_name)

c:\envs\myenv\Lib\site-packages\sagemaker\model.py:347: SageMakerV2DeprecationWarning: SKLearnModel is part of the SageMaker Python SDK v2, which is on path of deprecation. In v3, use `ModelBuilder` (`from sagemaker.serve import ModelBuilder`).
See https://github.com/aws/sagemaker-python-sdk/blob/master/migration.md for the migration guide. Set SAGEMAKER_SUPPRESS_V2_WARNING=1 to silence this warning.
  warn_v2_deprecation(
WARNING:sagemaker.deprecations:SKLearnModel is part of the SageMaker Python SDK v2, which is on path of deprecation. In v3, use `ModelBuilder` (`from sagemaker.serve import ModelBuilder`).
See https://github.com/aws/sagemaker-python-sdk/blob/master/migration.md for the migration guide. Set SAGEMAKER_SUPPRESS_V2_WARNING=1 to silence this warning.

Model Name:  Custom-sklearn-model-2026-09-14-06-26-26

In [62]:
endpoint_name = "Custom-sklearn-endpoint-" + strftime("%Y-%m-%d-%H-%M-%S", gmtime())
print("Endpoint Name:{}".format(endpoint_name))

predictor = model.deploy(initial_instance_count=1, instance_type='ml.m5.large', endpoint_name=endpoint_name)

Endpoint Name:Custom-sklearn-endpoint-2026-09-14-06-28-07

INFO:sagemaker:Creating model with name: Custom-sklearn-model-2026-09-14-06-26-26
INFO:sagemaker:Creating endpoint-config with name Custom-sklearn-endpoint-2026-09-14-06-28-07
INFO:sagemaker:Creating endpoint with name Custom-sklearn-endpoint-2026-09-14-06-28-07

------!

c:\envs\myenv\Lib\site-packages\sagemaker\base_predictor.py:140: SageMakerV2DeprecationWarning: SKLearnPredictor is part of the SageMaker Python SDK v2, which is on path of deprecation. In v3, use `sagemaker.core.resources.Endpoint`.
See https://github.com/aws/sagemaker-python-sdk/blob/master/migration.md for the migration guide. Set SAGEMAKER_SUPPRESS_V2_WARNING=1 to silence this warning.
  warn_v2_deprecation(
WARNING:sagemaker.deprecations:SKLearnPredictor is part of the SageMaker Python SDK v2, which is on path of deprecation. In v3, use `sagemaker.core.resources.Endpoint`.
See https://github.com/aws/sagemaker-python-sdk/blob/master/migration.md for the migration guide. Set SAGEMAKER_SUPPRESS_V2_WARNING=1 to silence this warning.

In [63]:
predictor
endpoint_name

'Custom-sklearn-endpoint-2026-09-14-06-28-07'

In [64]:
testX[features][0:2].values.tolist()

[[1646.0,
  0.0,
  2.5,
  0.0,
  3.0,
  1.0,
  25.0,
  0.6,
  200.0,
  2.0,
  5.0,
  211.0,
  1608.0,
  686.0,
  8.0,
  6.0,
  11.0,
  1.0,
  1.0,
  0.0],
 [1182.0,
  0.0,
  0.5,
  0.0,
  7.0,
  1.0,
  8.0,
  0.5,
  138.0,
  8.0,
  16.0,
  275.0,
  986.0,
  2563.0,
  19.0,
  17.0,
  19.0,
  1.0,
  0.0,
  0.0]]

In [65]:
print(predictor.predict(testX[features][0:2].values.tolist()))

[0 2]

In [66]:
sm_boto3.delete_endpoint(EndpointName=endpoint_name)

{'ResponseMetadata': {'RequestId': 'd2a783e0-9764-4f19-93b5-b30d5ddde13f',
  'HTTPStatusCode': 200,
  'HTTPHeaders': {'x-amzn-requestid': 'd2a783e0-9764-4f19-93b5-b30d5ddde13f',
   'strict-transport-security': 'max-age=47304000; includeSubDomains',
   'x-frame-options': 'DENY',
   'content-security-policy': "frame-ancestors 'none'",
   'cache-control': 'no-cache, no-store, must-revalidate',
   'x-content-type-options': 'nosniff',
   'content-type': 'application/x-amz-json-1.1',
   'date': 'Mon, 14 Sep 2026 06:33:25 GMT',
   'content-length': '0'},
  'RetryAttempts': 0}}